hash = "EA66A875E72C30F03330332BF0E7C1C81E187D4C6FF24F2F36B7E048EF6912F4"
imosidversion = "0.0.0-beta7"
parent = "instantosonboard.theme"
syntaxversion = "0"
target = "~/.local/share/onboard/themes/instantosonboard.theme"
