#!/bin/sh

#... all target ~/.xinitrc

#... xorg begin
#... xorg hash 2A06E4AC5CE07A9D70CB24B59B317EADCFF5DEF4CF87A66A8BE4DDDCD429B95B
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi
#... xorg end

#... session begin
#... session hash 79AE45B0BD98B938D812C4B9E94FE4F3132C7FBF1C2C72E9DD954EF85662AF35
exec startinstantos
#... session end
