hash = "A5BB9B3CAD4771CB2581F37BC4CDD7592B88E259B02DEAED65E5B98742596B4E"
imosidversion = "0.0.0-beta7"
parent = "globicons"
syntaxversion = "0"
target = "~/.config/rox.sourceforge.net/ROX-Filer/globicons"
