#!/bin/bash

echo "installing dotfiles for instantOS"

# don't run if newest version is already installed
if [ -n "$1" ] && [ "$1" = "-f" ]; then
    echo "forced run"
    shift 1
else

    # for use on other distros
    if iconf -i nodotfiles; then
        echo "instantdotfiles disabled"
        exit
    fi

    if [ -e /usr/share/instantdotfiles/versionhash ]; then
        if [ -e ~/.config/instantdotfiles/versionhash ]; then
            OLDHASH="$(cat /usr/share/instantdotfiles/versionhash)"
            NEWHASH="$(cat ~/.config/instantdotfiles/versionhash)"
            if [ "$OLDHASH" = "$NEWHASH" ]; then
                echo "newest dotfiles already installed"
                exit
            else
                cat /usr/share/instantdotfiles/versionhash >~/.config/instantdotfiles/versionhash
            fi
        else
            mkdir -p ~/.config/instantdotfiles &>/dev/null
            cat /usr/share/instantdotfiles/versionhash >~/.config/instantdotfiles/versionhash
        fi
    fi
fi

# run script as every user with a home directory
userrun() {
    REALUSERS="$(ls /home/ | grep -v '+')"
    for i in $REALUSERS; do
        echo "processing user $i"
        sudo su "$i" -c "$1"
    done
}

rootdotfiles() {
    cd /usr/share/instantdotfiles
    sudo ./rootinstall.sh
    userrun /usr/share/instantdotfiles/userinstall.sh
}

userdotfiles() {
    cd /usr/share/instantdotfiles
    ./userinstall.sh
}

if [ -z "$1" ]; then
    echo "single user dotfiles install"
    userdotfiles
else
    if [ -e /usr/share/instantdotfiles/$1.sh ]; then
        echo "instantOS font installer"
        /usr/share/instantdotfiles/$1.sh
    else
        echo "root dotfiles"
        rootdotfiles
    fi
fi
