#!/bin/bash

echo "installing dotfiles for instantOS"

# run script as every user with a home directory
userrun() {
    REALUSERS="$(ls /home/ | grep -v '+')"
    for i in $REALUSERS; do
        echo "processing user $i"
        sudo su "$i" -c "$1"
    done
}

rootdotfiles() {
    cd /usr/share/instantdotfiles
    sudo ./rootinstall.sh
    userrun /usr/share/instantdotfiles/userinstall.sh
}

userdotfiles() {
    cd /usr/share/instantdotfiles
    ./userinstall.sh
}

if [ -z "$1" ]; then
    echo "single user dotfiles install"
    userdotfiles
else
    if [ -e /usr/share/instantdotfiles/$1.sh ]; then
        echo "instantOS font installer"
        /usr/share/instantdotfiles/$1.sh
    else
        rootdotfiles
    fi
fi
