"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[line_break]
disabled = true

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[](bold red)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰎾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "
style = "red"

[julia]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = "󰛤 "
