return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	event = { "VeryLazy", "BufReadPost", "BufWritePost", "BufNewFile" },
	opts = {
		ensure_installed = {
			"bash",
			"c",
			"cpp",
			"css",
			"dart",
			"diff",
			"dockerfile",
			"go",
			"gomod",
			"html",
			"javascript",
			"json",
			"lua",
			"norg",
			"nginx",
			"regex",
			"sql",
			"sway",
			"terraform",
			"udev",
			"zathurarc",
			"zig",
			"make",
			"norg",
			"python",
			"rust",
			"markdown",
			"markdown_inline",
			"svelte",
			"toml",
			"tsx",
			"typescript",
		},
		ignore_install = { "latex" },
		sync_install = true,
		highlight = {
			enable = true,
			additional_vim_regex_highlighting = false,
			disable = { "latex" },
		},
		indent = { enable = true },
	},
	config = function(_, opts)
		require("nvim-treesitter.configs").setup(opts)
	end,
}
